# Generated by Django 6.0 on 2026-02-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('validity', models.CharField(max_length=20)),
            ],
        ),
    ]
