# Generated by Django 6.0 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
