# Generated by Django 6.0 on 2026-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='standard',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='validity',
            field=models.CharField(max_length=50),
        ),
    ]
