from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('certifications/', views.certifications, name='certifications'),
    path('accreditation/', views.accreditation, name='accreditation'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('certifications/iso-41001/', views.iso_41001, name='iso_41001'),
    path('certifications/iso-22301/', views.iso_22301, name='iso_22301'),
    path('certifications/iso-21001/', views.iso_21001, name='iso_21001'),
    path('certifications/iso-45001/', views.iso_45001, name='iso_45001'),
    path('certifications/iso-9001/', views.iso_9001, name='iso_9001'),
    path('certifications/iso-20000-1/', views.iso_20000_1, name='iso_20000_1'),
    path('certifications/iso-42001/', views.iso_42001, name='iso_42001'),
    path('certifications/iso-37001/', views.iso_37001, name='iso_37001'),
    path('certifications/iso-27001/', views.iso_27001, name='iso_27001'),
    path('certifications/iso-14001/', views.iso_14001, name='iso_14001'),
    path('certifications/iso-22000/', views.iso_22000, name='iso_22000'),
    path('certifications/iso-13485/', views.iso_13485, name='iso_13485'),
    path('certifications/iso-27701/', views.iso_27701, name='iso_27701'),
    path('certifications/iso-50001/', views.iso_50001, name='iso_50001'),
    path('certifications/iso-iec-27001/', views.iso_iec_27001, name='iso_iec_27001'),
    path('certifications/haccp/', views.HACCP, name='HACCP'),
    path('certifications/foodsafetycertification/', views.FoodSafetycertification, name='FoodSafetycertification'),
    path('certifications/ISOawarenesstraining/', views.ISOawarenesstraining, name='ISOawarenesstraining'),
    path('certifications/leadauditortraining/', views.LeadAuditorTraining, name='LeadAuditorTraining'),
    path('certifications/ISOinternalauditortraining/', views.InternalAuditorTraining, name='InternalAuditorTraining'),
    path('certifications/CE/', views.CE, name='CE'),
    path('certifications/ISO8124/', views.ISO8124, name='ISO8124'),
    path('certifications/energyaudit/', views.energyaudit, name='energyaudit'),
    path('certifications/safetyaudit/', views.safetyaudit, name='safetyaudit'),
    path('certifications/ISOtraining/', views.ISOTraining, name='ISOtraining'),
    path('DefenceIndustry/', views.DefenceIndustry, name='DefenceIndustry'),
    path('FoodandFoodProducts/', views.FoodandFoodProducts, name='FoodandFoodProducts'),
    path('HospitalityIndustry/', views.HospitalityIndustry, name='HospitalityIndustry'),
    path('TransportandLogistics/', views.TransportandLogistics, name='TransportandLogistics'),
    path('MedicalDevices/', views.MedicalDevices, name='MedicalDevices'),
    path('PublicSector/', views.PublicSector, name='PublicSector'),
    path('PharmaceuticalIndustry/', views.PharmaceuticalIndustry, name='PharmaceuticalIndustry'),
    path('QualityManagementSystem/', views.QualityManagementSystem, name='QualityManagementSystem'),
    path('SolarIndustry/', views.SolarIndustry, name='SolarIndustry'),
    path('TelecommunicationIndustry/', views.TelecommunicationIndustry, name='TelecommunicationIndustry'),
    path('AntiBriberyManagementSystem/', views.AntiBriberyManagementSystem, name='AntiBriberyManagementSystem'),
    path('ConstructionIndustry/', views.ConstructionIndustry, name='ConstructionIndustry'),
    path('ChemicalIndustry/', views.ChemicalIndustry, name='ChemicalIndustry'),
    path('ElectricalsAndElectronicsIndustry/', views.ElectricalsAndElectronicsIndustry, name='ElectricalsAndElectronicsIndustry'),
    path('EducationIndustry/', views.EducationIndustry, name='EducationIndustry'),
    path('EnergyIndustry/', views.EnergyIndustry, name='EnergyIndustry'),
    path('InformationTechnologyIndustry/', views.InformationTechnologyIndustry, name='InformationTechnologyIndustry'),
    path('TextileIndustry/', views.TextileIndustry, name='TextileIndustry'),
    path('AutomotiveIndustry/', views.AutomotiveIndustry, name='AutomotiveIndustry'),
    path('BankingAndFinance/', views.BankingAndFinance, name='BankingAndFinance'),
    path('EnvironmentalManagementSystem/', views.EnvironmentalManagementSystem, name='EnvironmentalManagementSystem'),
    path('HotelRestaurantAndLeisureService/', views.HotelRestaurantAndLeisureService, name='HotelRestaurantAndLeisureService'),
    path('Railways/', views.Railways, name='Railways'),
    path('ImportAndExportIndustry/', views.ImportAndExportIndustry, name='ImportAndExportIndustry'),
    path('ManufacturingIndustries/', views.ManufacturingIndustries, name='ManufacturingIndustries'),
    path('OilAndGasIndustry/', views.OilAndGasIndustry, name='OilAndGasIndustry'),
    path('TobaccoIndustry/', views.TobaccoIndustry, name='TobaccoIndustry'),
    path('TourismIndustries/', views.TourismIndustries, name='TourismIndustries'),
    path('OccupationalHealthAndSafetyManagementSystem/', views.OccupationalHealthAndSafetyManagementSystem, name='OccupationalHealthAndSafetyManagementSystem'),
    path("verify-certificate/", views.verify_certificate, name="verify_certificate"),


]
